// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logoutCancelBtn': string;
  'logoutConfirm': string;
  'logoutConfirmActions': string;
  'logoutConfirmBtn': string;
  'logoutConfirmMessage': string;
}
declare var cssExports: CssExports;
export = cssExports;
