// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'downloadButton': string;
  'empty': string;
}
declare var cssExports: CssExports;
export = cssExports;
