declare namespace VariablesExportScssNamespace {
  export interface IVariablesExportScss {
    accent: string;
    blur: string;
    border: string;
    card: string;
    charcoalGrey: string;
    colorPrimary: string;
    colorSecondary: string;
    compassWidth: string;
    dark: string;
    darkAlpha: string;
    darkLighter: string;
    darkMid: string;
    darkTranslucent: string;
    darkWithOverlay: string;
    font: string;
    fontBase: string;
    fontFeatureInfo: string;
    fontMono: string;
    fontPop: string;
    frontComponentZIndex: string;
    grey: string;
    greyLighter: string;
    greyLighter2: string;
    greyLightest: string;
    infoColor: string;
    inputBorder: string;
    inputHeight: string;
    inputHeightLarge: string;
    lg: string;
    logoHeight: string;
    logoPaddingHorizontal: string;
    logoPaddingVertical: string;
    logoSmallHeight: string;
    logoSmallPaddingHorizontal: string;
    logoSmallPaddingVertical: string;
    mapButtonColor: string;
    mapButtonTop: string;
    mapControlBg: string;
    mapControlColor: string;
    mapControlHoverBg: string;
    mapControlSeparator: string;
    mapControlShadow: string;
    mapControlSize: string;
    mapNavigationTop: string;
    md: string;
    mobile: string;
    modalBg: string;
    modalHighlight: string;
    modalText: string;
    muted: string;
    mutedForeground: string;
    notificationWindowZIndex: string;
    overlay: string;
    overlayInvert: string;
    padding: string;
    paddingMini: string;
    paddingSmall: string;
    paddingTiny: string;
    panelRadius: string;
    popover: string;
    radius40Button: string;
    radiusLarge: string;
    radiusMedium: string;
    radiusSmall: string;
    radiusXL: string;
    radiusXl: string;
    ring: string;
    ringWidth: string;
    scrollbarColor: string;
    scrollbarTrackColor: string;
    shadowLg: string;
    shadowMd: string;
    shadowSm: string;
    shadowXl: string;
    sideRailWidth: string;
    sm: string;
    spacing: string;
    statusBarBg: string;
    statusBarHeight: string;
    textBlack: string;
    textDark: string;
    textDarker: string;
    textLight: string;
    textLightDimmed: string;
    textLightTranslucent: string;
    textSuccess: string;
    textWarning: string;
    toolPrimaryColor: string;
    topToolbarHeight: string;
    trainerHeight: string;
    transparentDark: string;
    turquoiseBlue: string;
    workbenchMargin: string;
    workbenchMaxWidth: string;
    workbenchMinWidth: string;
    workbenchWidth: string;
    workflowPanelWidth: string;
  }
}

declare const VariablesExportScssModule: VariablesExportScssNamespace.IVariablesExportScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: VariablesExportScssNamespace.IVariablesExportScss;
};

export = VariablesExportScssModule;
